--- ../linuxcan/Makefile
+++ Makefile
@@ -66,9 +66,6 @@
 #----------------------------------------
 # included in build
 #----------------------------------------
-USERLIBS  += canlib
-USERLIBS  += linlib
-
 DRIVERS   += common
 DRIVERS   += leaf
 DRIVERS   += mhydra
@@ -87,7 +84,7 @@ KV_DEBUG_ON ?= 0
 export KV_DEBUG_ON
 
 #---------------------------------
-SUBDIRS   = $(USERLIBS) $(DRIVERS)
+SUBDIRS   = $(DRIVERS)
 
 reverse=$(if $(1),$(call reverse,$(wordlist 2,$(words $(1)),$(1)))) $(firstword $(1))
 
@@ -104,7 +101,7 @@ endef
 
 #---------------------------------------------------------------------------
 # RULES
-.PHONY: print_versions_start canlib linlib common leaf mhydra pcican pcican2 usbcanII virtualcan pciefd install uninstall clean check load
+.PHONY: print_versions_start common leaf mhydra pcican pcican2 usbcanII virtualcan pciefd install uninstall clean check load
 
 all: print_versions_start $(SUBDIRS)
 	@echo
@@ -117,12 +114,6 @@ print_versions_start:
 	@$(call check_for_kvaser_usb_devices)
 	@$(call check_for_secure_boot)
 
-canlib:
-	$(MAKE) -C canlib examples
-
-linlib: canlib
-	$(MAKE) -C linlib
-
 common:
 	@cd ./common; $(MAKE) kv_module
 
@@ -149,30 +140,21 @@ pciefd: common
 
 install:
 	@for dir in $(DRIVERS) ; do cd $$dir; echo Installing $$dir;./installscript.sh || exit 1; cd ..; done
-	$(MAKE) -C canlib install
-	$(MAKE) -C linlib install
 
 uninstall:
 	@for dir in $(call reverse,$(DRIVERS)) ; do cd $$dir; echo Uninstalling $$dir;./uninstallscript.sh || exit 1; cd ..; done
-	$(MAKE) -C canlib uninstall
-	$(MAKE) -C linlib uninstall
 	rm -f /etc/udev/rules.d/10-kvaser.rules
 	rm -f /etc/modules-load.d/kvaser.conf
 
 purge:
 	@for dir in $(call reverse,$(DRIVERS)) ; do cd $$dir; echo Uninstalling $$dir;./uninstallscript.sh -p || exit 1; cd ..; done
-	$(MAKE) -C canlib uninstall
-	$(MAKE) -C linlib uninstall
 	rm -f /etc/udev/rules.d/10-kvaser.rules
 	rm -f /etc/modules-load.d/kvaser.conf
 
 load:
 	@for dir in $(DRIVERS) ; do cd $$dir; echo Installing $$dir;./installscript.sh load || exit 1; cd ..; done
-	$(MAKE) -C canlib install
-	$(MAKE) -C linlib install
 
 check:
-	$(MAKE) -C canlib check
 	@for dir in $(DRIVERS) ; do cd $$dir; $(MAKE) check; cd ..; done
 
 clean:
